POST http://localhost:9000/api/addDevice
Content-Type: "application/json"

{
    "AccessPointData": [
        {
            "Building": "Wing A",
            "Floor": "Floor 1",
            "Section": "ICU",
            "AccessPointName": "Access Point 1",
            "BSSID": "ca:97:df:29:82:54",
            "SSID": "42"
        },
        {
            "Building": "Wing A",
            "Floor": "Floor 3",
            "Section": "General Ward",
            "AccessPointName": "Access Point 2",
            "BSSID": "ca:97:df:29:82:55",
            "SSID": "43"
        }
    ]
}